import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Animalerie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body>
        <div className="flex flew-col gap-4">
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
