import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Animalerie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
